/********************************************************************************************
 *    _ ____  ___             _         _     ___              _                        _
 *   (_)__ / | _ \_ _ ___  __| |_  _ __| |_  |   \ _____ _____| |___ _ __ _ __  ___ _ _| |_
 *   | ||_ \ |  _/ '_/ _ \/ _` | || / _|  _| | |) / -_) V / -_) / _ \ '_ \ '  \/ -_) ' \  _|
 *   |_|___/ |_| |_| \___/\__,_|\_,_\__|\__| |___/\___|\_/\___|_\___/ .__/_|_|_\___|_||_\__|
 *                                                                  |_|
 *                           -----------------------------------
 *                          Copyright i3 Product Development 2024
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * @file      definitions.h/.c
 * @brief     A minimal implementation of Reach data access.  Auto-generated by a Python script.
 * @copyright 2023-2024 i3 Product Development. All Rights Reserved.
 *
 * Original Author: Chuck Peplinski
 * Script Author: Joseph Peplinski
 * Script Author: Andrew Carlson
 *
 ********************************************************************************************/

#include "definitions.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "i3_log.h"
#include "app_version.h"
#include "cr_stack.h"

const cr_DeviceInfoResponse device_info = {
    .device_name = "Thunderboard",
    .manufacturer = "Silicon Labs",
    .device_description = "A demo of Reach features",
    .services = cr_ServiceIds_PARAMETER_REPO | cr_ServiceIds_FILES | cr_ServiceIds_COMMANDS | cr_ServiceIds_CLI
};
cr_ParameterValue sCr_param_val[NUM_PARAMS];
const cr_ParameterInfo param_desc[NUM_PARAMS] = {
    {
        .id = PARAM_USER_DEVICE_NAME,
        .name = "User Device Name",
        .has_description = true,
        .description = "The advertised BLE name",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_NONVOLATILE,
        .which_desc = cr_ParameterDataType_STRING + cr_ParameterInfo_uint32_desc_tag,
        .desc.string_desc.max_size = 29
    },
    {
        .id = PARAM_UPTIME,
        .name = "Uptime",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_INT64 + cr_ParameterInfo_uint32_desc_tag,
        .desc.int64_desc.has_units = true,
        .desc.int64_desc.units = "milliseconds"
    },
    {
        .id = PARAM_BUTTON_PRESSED,
        .name = "Button Pressed",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_BOOL + cr_ParameterInfo_uint32_desc_tag,
        .desc.bool_desc.has_pei_id = true,
        .desc.bool_desc.pei_id = PARAM_EI_IDENTIFY_SWITCH
    },
    {
        .id = PARAM_IDENTIFY_LED,
        .name = "Identify LED",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_BOOL + cr_ParameterInfo_uint32_desc_tag,
        .desc.bool_desc.has_pei_id = true,
        .desc.bool_desc.pei_id = PARAM_EI_IDENTIFY_LED
    },
    {
        .id = PARAM_RGB_LED_STATE,
        .name = "RGB LED State",
        .has_description = true,
        .description = "A demo of a bitfield",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_BIT_FIELD + cr_ParameterInfo_uint32_desc_tag,
        .desc.bitfield_desc.bits_available = 3,
        .desc.bitfield_desc.has_pei_id = true,
        .desc.bitfield_desc.pei_id = PARAM_EI_BITTYBIT
    },
    {
        .id = PARAM_COMMAND_LINE_COLOR,
        .name = "Command Line Color",
        .has_description = true,
        .description = "Reset on disconnection",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_ENUMERATION + cr_ParameterInfo_uint32_desc_tag,
        .desc.enum_desc.has_range_min = true,
        .desc.enum_desc.range_min = 0,
        .desc.enum_desc.has_range_max = true,
        .desc.enum_desc.range_max = 7,
        .desc.enum_desc.has_pei_id = true,
        .desc.enum_desc.pei_id = PARAM_EI_CLI_COLOR
    },
    {
        .id = PARAM_IDENTIFY,
        .name = "Identify",
        .has_description = true,
        .description = "Turn on to blink the yellow LED",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_BOOL + cr_ParameterInfo_uint32_desc_tag,
        .desc.bool_desc.has_default_value = true,
        .desc.bool_desc.default_value = false
    },
    {
        .id = PARAM_IDENTIFY_INTERVAL,
        .name = "Identify Interval",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_NONVOLATILE,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = 0.01,
        .desc.float32_desc.has_default_value = true,
        .desc.float32_desc.default_value = 1,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 60
    },
    {
        .id = PARAM_RELATIVE_HUMIDITY,
        .name = "Relative Humidity",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "%",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = 0.01,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 100,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 1
    },
    {
        .id = PARAM_TEMPERATURE,
        .name = "Temperature",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "° C",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = -57,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 99,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 1
    },
    {
        .id = PARAM_LIGHT_LEVEL,
        .name = "Light Level",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "lux",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = 0,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 1000,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 1
    },
    {
        .id = PARAM_UV_INDEX,
        .name = "UV Index",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "W/sq meter",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = 0,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 100,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 1
    },
    {
        .id = PARAM_MAGNETIC_FIELD_STRENGTH,
        .name = "Magnetic Field Strength",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "millitesla",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = 0,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 5000,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 1
    },
    {
        .id = PARAM_ACCELERATION_X_AXIS,
        .name = "Acceleration (X axis)",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "m/s",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = -50,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 50,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 2
    },
    {
        .id = PARAM_ACCELERATION_Y_AXIS,
        .name = "Acceleration (Y axis)",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "m/s",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = -50,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 50,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 2
    },
    {
        .id = PARAM_ACCELERATION_Z_AXIS,
        .name = "Acceleration (Z axis)",
        .has_description = true,
        .description = "Read from Thunderboard Sensor",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_FLOAT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.float32_desc.has_units = true,
        .desc.float32_desc.units = "m/s",
        .desc.float32_desc.has_range_min = true,
        .desc.float32_desc.range_min = -50,
        .desc.float32_desc.has_range_max = true,
        .desc.float32_desc.range_max = 50,
        .desc.float32_desc.has_precision = true,
        .desc.float32_desc.precision = 2
    },
    {
        .id = PARAM_TIMEZONE_ENABLED,
        .name = "Timezone Enabled",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_NONVOLATILE,
        .which_desc = cr_ParameterDataType_BOOL + cr_ParameterInfo_uint32_desc_tag,
        .desc.bool_desc.has_default_value = true,
        .desc.bool_desc.default_value = true
    },
    {
        .id = PARAM_TIMEZONE_OFFSET,
        .name = "Timezone Offset",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_NONVOLATILE,
        .which_desc = cr_ParameterDataType_INT32 + cr_ParameterInfo_uint32_desc_tag,
        .desc.int32_desc.has_units = true,
        .desc.int32_desc.units = "seconds",
        .desc.int32_desc.has_range_min = true,
        .desc.int32_desc.range_min = -43200,
        .desc.int32_desc.has_default_value = true,
        .desc.int32_desc.default_value = 0,
        .desc.int32_desc.has_range_max = true,
        .desc.int32_desc.range_max = 43200
    },
    {
        .id = PARAM_BT_DEVICE_ADDRESS,
        .name = "BT Device Address",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_RAM,
        .which_desc = cr_ParameterDataType_BYTE_ARRAY + cr_ParameterInfo_uint32_desc_tag,
        .desc.bytearray_desc.max_size = 6
    }
};
const cr_ParameterNotifyConfig sParamNotifyInit[NUM_INIT_NOTIFICATIONS] = {
    {
        .parameter_id = PARAM_IDENTIFY_LED,
        .minimum_notification_period = 302,
        .minimum_delta = 1
    },
    {
        .parameter_id = PARAM_IDENTIFY,
        .minimum_notification_period = 501,
        .minimum_delta = 1
    },
    {
        .parameter_id = PARAM_RELATIVE_HUMIDITY,
        .minimum_notification_period = 2010,
        .maximum_notification_period = 60000,
        .minimum_delta = 1
    },
    {
        .parameter_id = PARAM_TEMPERATURE,
        .minimum_notification_period = 2020,
        .maximum_notification_period = 60000,
        .minimum_delta = 0.2
    },
    {
        .parameter_id = PARAM_LIGHT_LEVEL,
        .minimum_notification_period = 1020,
        .maximum_notification_period = 60000,
        .minimum_delta = 20
    },
    {
        .parameter_id = PARAM_UV_INDEX,
        .minimum_notification_period = 3031,
        .maximum_notification_period = 60000,
        .minimum_delta = 1
    },
    {
        .parameter_id = PARAM_MAGNETIC_FIELD_STRENGTH,
        .minimum_notification_period = 3019,
        .maximum_notification_period = 60000,
        .minimum_delta = 0.2
    },
    {
        .parameter_id = PARAM_ACCELERATION_X_AXIS,
        .minimum_notification_period = 2037,
        .minimum_delta = 0.2
    },
    {
        .parameter_id = PARAM_ACCELERATION_Y_AXIS,
        .minimum_notification_period = 2047,
        .minimum_delta = 0.2
    },
    {
        .parameter_id = PARAM_ACCELERATION_Z_AXIS,
        .minimum_notification_period = 2057,
        .minimum_delta = 0.2
    }
};
static const cr_ParamExKey __cr_gen_pei_identify_switch_labels[] = {
    {
        .id = 0,
        .name = "Not Identifying"
    },
    {
        .id = 1,
        .name = "Identifying"
    }
};
static const cr_ParamExKey __cr_gen_pei_identify_led_labels[] = {
    {
        .id = 0,
        .name = "Off"
    },
    {
        .id = 1,
        .name = "Illuminated"
    }
};
static const cr_ParamExKey __cr_gen_pei_timezone_labels[] = {
    {
        .id = 0,
        .name = "Non-Timezoned"
    },
    {
        .id = 1,
        .name = "Timezoned"
    }
};
static const cr_ParamExKey __cr_gen_pei_bittybit_labels[] = {
    {
        .id = 0,
        .name = "Red"
    },
    {
        .id = 1,
        .name = "Green"
    },
    {
        .id = 2,
        .name = "Blue"
    }
};
static const cr_ParamExKey __cr_gen_pei_cli_color_labels[] = {
    {
        .id = 0,
        .name = "Off"
    },
    {
        .id = 1,
        .name = "Red"
    },
    {
        .id = 2,
        .name = "Green"
    },
    {
        .id = 3,
        .name = "Yellow"
    },
    {
        .id = 4,
        .name = "Blue"
    },
    {
        .id = 5,
        .name = "Magenta"
    },
    {
        .id = 6,
        .name = "Cyan"
    },
    {
        .id = 7,
        .name = "White"
    }
};
const cr_gen_param_ex_t param_ex_desc[NUM_EX_PARAMS] = {
    {
        .pei_id = PARAM_EI_IDENTIFY_SWITCH,
        .data_type = cr_ParameterDataType_BOOL,
        .num_labels = 2,
        .labels = __cr_gen_pei_identify_switch_labels
    },
    {
        .pei_id = PARAM_EI_IDENTIFY_LED,
        .data_type = cr_ParameterDataType_BOOL,
        .num_labels = 2,
        .labels = __cr_gen_pei_identify_led_labels
    },
    {
        .pei_id = PARAM_EI_TIMEZONE,
        .data_type = cr_ParameterDataType_BOOL,
        .num_labels = 2,
        .labels = __cr_gen_pei_timezone_labels
    },
    {
        .pei_id = PARAM_EI_BITTYBIT,
        .data_type = cr_ParameterDataType_BIT_FIELD,
        .num_labels = 3,
        .labels = __cr_gen_pei_bittybit_labels
    },
    {
        .pei_id = PARAM_EI_CLI_COLOR,
        .data_type = cr_ParameterDataType_ENUMERATION,
        .num_labels = 8,
        .labels = __cr_gen_pei_cli_color_labels
    }
};
cr_FileInfo file_descriptions[NUM_FILES] = {
    {
        .file_id = FILE_IO_TXT,
        .file_name = "io.txt",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_NONVOLATILE,
        .require_checksum = false,
        .has_maximum_size_bytes = true,
        .maximum_size_bytes = 2048
    },
    {
        .file_id = FILE_CYGNUS_REACH_LOGO_PNG,
        .file_name = "cygnus-reach-logo.png",
        .access = cr_AccessLevel_READ,
        .storage_location = cr_StorageLocation_NONVOLATILE,
        .require_checksum = false,
        .has_maximum_size_bytes = true,
        .maximum_size_bytes = 17900
    },
    {
        .file_id = FILE_DEV_NULL,
        .file_name = "dev_null",
        .access = cr_AccessLevel_READ_WRITE,
        .storage_location = cr_StorageLocation_RAM,
        .require_checksum = false,
        .has_maximum_size_bytes = true,
        .maximum_size_bytes = 100000
    }
};
const cr_CommandInfo command_desc[NUM_COMMANDS] = {
    {
        .id = COMMAND_RESET_DEFAULTS,
        .name = "Reset Defaults",
        .has_description = true,
        .description = "Restore factory values."
    },
    {
        .id = COMMAND_CLICK_FOR_WISDOM,
        .name = "Click for Wisdom",
        .has_description = true,
        .description = "Press it and find out"
    },
    {
        .id = COMMAND_NO_LOGGING,
        .name = "No logging",
        .has_description = true,
        .description = "lm 0"
    },
    {
        .id = COMMAND_MUCH_LOGGING,
        .name = "Much logging",
        .has_description = true,
        .description = "lm 1c7"
    },
    {
        .id = COMMAND_NOTIFICATIONS_ON,
        .name = "Notifications On",
        .has_description = true,
        .description = "Enable notifications on changes"
    },
    {
        .id = COMMAND_NOTIFICATIONS_OFF,
        .name = "Notifications Off",
        .has_description = true,
        .description = "disable all notifications"
    },
    {
        .id = COMMAND_REMOTE_CLI_ON,
        .name = "Remote CLI On",
        .has_description = true,
        .description = "To interact remotely"
    },
    {
        .id = COMMAND_REMOTE_CLI_OFF,
        .name = "Remote CLI Off",
        .has_description = true,
        .description = "Avoids heavy communication load"
    }
};

